// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v4.25.3
// source: pb/processor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentFileStorageType int32

const (
	ContentFileStorageType_StorageTypeEs ContentFileStorageType = 0
	ContentFileStorageType_StorageTypeFs ContentFileStorageType = 1
)

// Enum value maps for ContentFileStorageType.
var (
	ContentFileStorageType_name = map[int32]string{
		0: "StorageTypeEs",
		1: "StorageTypeFs",
	}
	ContentFileStorageType_value = map[string]int32{
		"StorageTypeEs": 0,
		"StorageTypeFs": 1,
	}
)

func (x ContentFileStorageType) Enum() *ContentFileStorageType {
	p := new(ContentFileStorageType)
	*p = x
	return p
}

func (x ContentFileStorageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentFileStorageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_processor_proto_enumTypes[0].Descriptor()
}

func (ContentFileStorageType) Type() protoreflect.EnumType {
	return &file_pb_processor_proto_enumTypes[0]
}

func (x ContentFileStorageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentFileStorageType.Descriptor instead.
func (ContentFileStorageType) EnumDescriptor() ([]byte, []int) {
	return file_pb_processor_proto_rawDescGZIP(), []int{0}
}

type NewsProcessMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContentFileKeys []string               `protobuf:"bytes,2,rep,name=content_file_keys,json=contentFileKeys,proto3" json:"content_file_keys,omitempty"`
	StorageType     ContentFileStorageType `protobuf:"varint,3,opt,name=storage_type,json=storageType,proto3,enum=ContentFileStorageType" json:"storage_type,omitempty"`
}

func (x *NewsProcessMessage) Reset() {
	*x = NewsProcessMessage{}
	mi := &file_pb_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsProcessMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsProcessMessage) ProtoMessage() {}

func (x *NewsProcessMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsProcessMessage.ProtoReflect.Descriptor instead.
func (*NewsProcessMessage) Descriptor() ([]byte, []int) {
	return file_pb_processor_proto_rawDescGZIP(), []int{0}
}

func (x *NewsProcessMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewsProcessMessage) GetContentFileKeys() []string {
	if x != nil {
		return x.ContentFileKeys
	}
	return nil
}

func (x *NewsProcessMessage) GetStorageType() ContentFileStorageType {
	if x != nil {
		return x.StorageType
	}
	return ContentFileStorageType_StorageTypeEs
}

var File_pb_processor_proto protoreflect.FileDescriptor

var file_pb_processor_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x4e, 0x65, 0x77, 0x73, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x3a, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x2a, 0x3e, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45, 0x73, 0x10, 0x00,
	0x12, 0x11, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x46,
	0x73, 0x10, 0x01, 0x42, 0x32, 0x0a, 0x0e, 0x63, 0x61, 0x69, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x42, 0x0b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x50, 0x62, 0x5a, 0x13, 0x63, 0x61, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_processor_proto_rawDescOnce sync.Once
	file_pb_processor_proto_rawDescData = file_pb_processor_proto_rawDesc
)

func file_pb_processor_proto_rawDescGZIP() []byte {
	file_pb_processor_proto_rawDescOnce.Do(func() {
		file_pb_processor_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_processor_proto_rawDescData)
	})
	return file_pb_processor_proto_rawDescData
}

var file_pb_processor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_processor_proto_goTypes = []any{
	(ContentFileStorageType)(0), // 0: ContentFileStorageType
	(*NewsProcessMessage)(nil),  // 1: NewsProcessMessage
}
var file_pb_processor_proto_depIdxs = []int32{
	0, // 0: NewsProcessMessage.storage_type:type_name -> ContentFileStorageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_processor_proto_init() }
func file_pb_processor_proto_init() {
	if File_pb_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_processor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_processor_proto_goTypes,
		DependencyIndexes: file_pb_processor_proto_depIdxs,
		EnumInfos:         file_pb_processor_proto_enumTypes,
		MessageInfos:      file_pb_processor_proto_msgTypes,
	}.Build()
	File_pb_processor_proto = out.File
	file_pb_processor_proto_rawDesc = nil
	file_pb_processor_proto_goTypes = nil
	file_pb_processor_proto_depIdxs = nil
}
